language: scala
scala:
- 2.11.4
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master
  - /^[0-9].[0-9].[0-9]$/
cache:
  directories:
  - $HOME/.m2

before_install:
- test "$TRAVIS_PULL_REQUEST" == "false" && git clone -b travis `git config --get remote.origin.url` target/travis || true

install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "Not a PR Build" && [ "IS_${TRAVIS_TAG}" != "IS_" ] && echo "Is tag build $TRAVIS_TAG" || echo "."'
- '[ "IS_${TRAVIS_TAG}" != "IS_" ] && mvn versions:set -DnewVersion=$TRAVIS_TAG || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "Deploying..." && mvn deploy site-deploy -DskipTests=true --settings target/travis/settings.xml -Dgithub.global.oauth2Token=$GITHUB_TOKEN || echo "Testing..." && mvn test -B'

after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sbt ++2.11.4 coverageAggregate || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sbt ++2.11.4 coveralls || true'

env:
  global:
  - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
  - secure: C6EtHI0vV7436ocVewCB1TICsPBccGdfdzvWAeNdmIR+Pz4qPB0K8Sk2YHXXw270LLLonh4+1a7L9U6BoJPqdNwXQOZREes9aEmgYbR4C4YQuO16SDFKREzPngwvetzQAcHa9qrkMcSW9mx0/yuMfYIjMVarUuLblExZyGmkrS3vCVySXkm8KfnIdEAHv6Rqi4wC59tyIuGER+JJyCIlF0WAtLFQLADhzEGAc6Y5S+6uvpnS4dtt5jcWTYGFUOlrsG8y21+At1xxlVuJVF7+VRCbqO6eQK4eWhTLBitOUOw+f/YI5SMg8E/1qh0RcGXV7cCMqQyF+HQjiwOInXg1WzmCEk23PN2pYum4DB12SGLK25JAwrW1IiQtQ4hvC/YXAmgBmrQalgTpF3S33zYJva0HRGG/FlWoRJ8N7DBJhMkbex56hmZWLP6w0xH5L+tGTurxKhraaaDuQYwm4HyB8sb6mDc5DwlYEDnk0/AgxTn1DMDPDOGGx57qqqNGfPfCn1gT7tW5zd+xjhwIEvWlC9xOi5TVC22wn6PzA8BskKrmq7wahYVwoMogL1J7caD+oFBqQwKt2cpkpGfp9eJbMu/zu5TfM9DZkyAAiAf87d/Suv97leOTgzaUy1+1nxYgm05j2Tr7XGFTLJPHtsFaQtR5tygDmR2xqXTHtjjJ6/Q=
  - secure: e2saLM2i5J2Z+ECpgMEXvvSSFqRq6sJlVliJTXp0JjiGNzM6kWB6N28DjkOSjM9fVgKqoyXFENDk2uVFnokOy3tEqePaaCItCqT3LFt24ZvNekvEs7saVZTllJE03Xvr5IktXMaUal4t1truvmQnVx4n+ZkvvNCHLM3T3yNSlxa2WC/z2G/eR/o3vvY/ags2Oz0ijox+gylzei7rY5Ax2OIEmX9OWSuwtftAFfgZnnZhjoPek0IwljWTmrqpFmIqsVlov3c1Jx7QtCFAlbeX+uKYQE4lUXw6OjkBlGvzslPLK9I7wy5LTq/n3RCauCSRp9AjV2dJR+uacHTKZtQV6U2UFGEPuD9Z7eswoCNL5Q1Vm3bCI5uxrzST4rV+CvGNgvxiOLuqlgmB+CKPtB4gcntKE725Sc3uHjtfVCKQsropJ19HtfB/g1dXM5iC9W5uK8Gk+PTWhvScbAiZvx21dztPZzU3OLCO1KJneUV2H3mWurmx7owd9H79RzCuvkGI9PwUCKdb85KLEESss9jF9cDoCCG/K0guUOjcrUiwHZ8j671XtFT00jESxYdeW9Mmi2WzWbjVD5DMd7ouIKojFmwXSs1Mb6zpD7yZ5RfVcjPBvFz+uflpFAME1Q1lG5dbwvAFs4JLwDICmgkFTCLlGua2s8dzkpHOcUUEycRrveA=
  - secure: iGY4XKyqF79LqEHMoF9Uca7quyKiQkDZEijCn9KXRLLKsJv4MS1/YESW6ZjVfcq8UVJ1viroteMJtPMZeTjhqjq0/na2s6aSIDZrwcM1PhYMJzW5r8vr+jrvdBR/aaoxpzfI29rYeA2oqRwh9DDdHQommZKapK8tfHuPsjS5JxaH/n7PcET3MAumkxpx8Mjnkhcc1xTM48wVBPO4kl0A+xr90gFNsJj2+9mQ4P7ngiBsGX0tdRfIrfZS+1D92R5OAanNxqDlj+vGeXkg4DryD55G2LkAKJOs4Ga1w7ish2b4xqvZP+nmwc63fsmhyYMpcM2yLDcGlNdZdfKKqW3Ycqrlm4W15f4xJ5U8HH3fJlgtsfkkOAMVOT0fCCfpDXVxinyl3keHfsO+CEWK+GdNhvbh0l6niFUyXdIp6a+kVXsnoI4wch60jTNJOjrmE6EM3WH5QT770/9aUvIgJxGsMXBddi653y07C9QjY7CRUdHD/w6WPexkKY89i1HfcuwHaVgVvvx0nFh/Q0CFSjRrRz65dmKqJowMTBupRERnGyy3k8YKbokY3eyOLlOVTA+dNqI4DNDUbsSrhFFFe+Wum2hpZUd2jNdXqp9VU66fxQ1gI484so6Go6VGoyzJg+WjSZlRP3VQ6EMEPK0kAjHWYfQIHPG9WnVwIp5b0v07kp4=
